DROP SEQUENCE IF EXISTS hit_seq;
DROP TABLE IF EXISTS hits;

CREATE SEQUENCE IF NOT EXISTS hit_seq START 1 INCREMENT 1;
CREATE TABLE IF NOT EXISTS hits (
    id INT8 PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);